# The Compose file is a YAML file defining services, networks, and volumes for a Docker application
# Para nuestro inception, necesitamos uno para nginx, wordprss y mariadb
# https://docs.docker.com/compose/compose-file/
version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    # Como es un array, podemos poner varios - 
    networks:
      - inception
    # Los volúmenes permiten almacenar el contenido de un disco local de manera "permanente"
    # El path es el mismo para todos los nginx, igual que es el mismo para todos los mariadb, etc.
    volumes:
      - mariadb_volume:/var/lib/mysql
    # hacemos un restart cada vez que iniciemos
    # Dónde lo creamos
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - "3306"
    restart: always
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    # Exposes port 443 for external usage
    ports:
      - "8443:443"
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: always
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}

      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USR: ${WP_ADMIN_USR}
      WP_ADMIN_PWD: ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USR: ${WP_USR}
      WP_PWD: ${WP_PWD}
      WP_EMAIL: ${WP_EMAIL}

# Si cierras un contenedor, se borran todos los datos. Por eso lo guadamos localmente en una carpeta
# Aqui lo configuramos
volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/frmurcia/data/mariadb'
  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/frmurcia/data/wordpress'

networks:
  inception:
    driver: bridge
